### ISSUE TITLE
laser_filter crashes without ranges

### ISSUE THREAD

**Issue by bwehbe** [rock-drivers/drivers-laser_filter#3]
if I use a noiseFilter and the ranges of the LaserScan is not set, the filter crashes.

example:

    NoiseFilter noiseFilter;
    LaserScan = base::samples::LaserScan;
    MyLaserScan = base::samples::LaserScan;

    noiseFilter.filter(LaserScan, MyLaserScan);

but it works if setting the ranges of the LaserScan to a value, for e.g.

    MyLaserScan.ranges.resize(10, 0);

**Comment by jmachowinski** [comment]
Fixed.
The use case of filtering an empty scan is rather odd...
